# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='name',
            field=models.CharField(default='type', max_length=30),
        ),
    ]
