# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_counting_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('answer', models.CharField(default='', max_length=30)),
                ('current', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='counting',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
