# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_auto_20160606_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='current',
            field=models.CharField(max_length=30),
        ),
    ]
