# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0008_auto_20160606_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lives',
            field=models.IntegerField(default=5),
        ),
    ]
