# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0010_auto_20160607_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AddField(
            model_name='player',
            name='lives',
            field=models.IntegerField(default=8),
        ),
    ]
