# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0011_auto_20160607_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
